//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LauroCRUD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Pessoa
    {
        [Required(ErrorMessage = "Nome completo obrigatório")]
        public string nome { get; set; }
        public int cargoId { get; set; }
        [Required(ErrorMessage = "Data de Nascimento obrigatória")]
        [DataType(DataType.Date)]
        public System.DateTime data { get; set; }
        [Required(ErrorMessage = "E-mail Obrigatório")]
        [RegularExpression(".+\\@.+\\..+", ErrorMessage = "Informe um email válido...")]
        public string email { get; set; }
        [Required(ErrorMessage = "Celular obrigatório")]
        public string celular { get; set; }
        public int id { get; set; }
        [Required(ErrorMessage = "CPF Obrigatório")]
        public string cpf { get; set; }
    
        public virtual cargo cargo { get; set; }
    }
}


